import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Components from "../components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Esther Regina Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full min-h-screen bg-white flex-col">
          <Components.Menu/>
          <div className="flex min-h-screen justify-center">
            {/* <div className="flex w-full max-w-[1400px] p-5"> */}
              {children}
            {/* </div> */}
          </div>
          <Components.Footer/>
        </div>
      </body>
    </html>
  );
}
